#!/bin/sh
### BEGIN INIT INFO
# Provides:          taxi
# Required-Start:    $kannel
# Should-Start:      $local_fs $network
# Should-Stop:       $local_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Taxi button python daemon
# Description:       Python daemon to read COM-port through USB and react to button pushes
### END INIT INFO

. /lib/lsb/init-functions

TAXI=/usr/local/bin

PATH=$TAXI:$PATH

case "$1" in
  start)
    log_daemon_msg "Starting TAXI daemon"
    taxi-daemon.py start
    log_end_msg 0
    ;;

  stop)
    log_daemon_msg "Stopping TAXI daemon"
    taxi-daemon.py stop
    log_end_msg 0
    ;;

  reload)
    log_daemon_msg "Restartting TAXI daemon"
    taxi-daemon.py restart
    log_end_msg 0
    exit 1
    ;;

  restart|force-reload)
    $0 reload
    ;;

  *)
    echo "Usage: $0 {start|stop|restart|force-reload}"
    exit 1

esac

exit 0
